---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Relise.Name }}-service
  labels:
    env: prod
    owner: admito
spec:
  selector:
    project: {{ .Relise.Name }}
  ports:
  - name: {{ .Relise.Name }}-listener
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
...
