---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env: prod
    owner: admito
spec:
  selector:
    project: cio
  ports:
  - name: app-listener
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
...
